### ISSUE TITLE
Only works with black bg?

### ISSUE THREAD

**Issue by fluxxus** [hcastillaq/starfield#1]
Hey,

Really love your script, but it seems that it only works when pure black(or really dark color) is used as background.

Is there a way to make it look nice with other colors, or preferably when applied with transparent background?

Thx

**Comment by hcastillaq** [comment]
hello, in theory it works for any background color, the idea is to find a combination between the background color of the particle and its shadow.

<img width="965" alt="image" src="https://github.com/hcastillaq/starfield/assets/14365292/4a4a5a95-fc66-4723-9aa5-01c523d213f5">

**Comment by fluxxus** [comment]
@hcastillaq Thanks for the clarification. I'll do some trial and error then :)
